# Generated by Django 4.0 on 2023-05-12 17:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('unique_id', models.CharField(default='2022/TR/10', max_length=50)),
                ('user_type', models.CharField(default='Student', max_length=10)),
                ('status', models.CharField(default='Absent', max_length=10)),
                ('subject', models.CharField(default='English', max_length=20)),
                ('time_in', models.DateTimeField()),
                ('time_out', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(help_text='e.g. Primary or Secondary', max_length=20, verbose_name='School Type')),
                ('headteacher', models.CharField(blank=True, max_length=20)),
                ('district', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'School',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('unique_id', models.CharField(default='2022/STD/1', max_length=50)),
                ('birthday', models.DateField()),
                ('student_class', models.CharField(max_length=20)),
                ('school', models.CharField(default='Makerere Primary', max_length=50)),
                ('level', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=50)),
                ('avatar', models.ImageField(default='user.png', upload_to='student')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subject',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('unique_id', models.CharField(default='2022/TR/1', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('school', models.CharField(default='Makerere Primary', max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('avatar', models.ImageField(default='user.png', upload_to='teacher')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ManyToManyField(related_name='teachers', to='api.Subject', verbose_name='Subjects')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teacher',
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50, verbose_name='Event Title')),
                ('eventDescriptionLabel', models.CharField(max_length=50, verbose_name='Description')),
                ('eventLocationLabel', models.CharField(max_length=20, verbose_name='Venue')),
                ('repeatField', models.CharField(max_length=10, verbose_name='Repeat Field')),
                ('image', models.ImageField(default='figma-icon.svg', upload_to='timetable')),
                ('className', models.CharField(default='fullcalendar-custom-event-holidays', max_length=50, verbose_name='Class Theme')),
                ('start', models.DateTimeField(verbose_name='Start Time')),
                ('end', models.DateTimeField(verbose_name='End Time')),
                ('allDays', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guestsField', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='api.teacher', verbose_name='teacher')),
            ],
            options={
                'verbose_name': 'Timetable',
                'verbose_name_plural': 'Timetable',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('position', models.CharField(default='admin', max_length=20)),
                ('email_verified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('avatar', models.ImageField(default='user.png', upload_to='profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
