# Generated by Django 4.0 on 2022-06-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avatar',
            field=models.ImageField(default='user.png', upload_to='student'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='avatar',
            field=models.ImageField(default='user.png', upload_to='teacher'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(default='Absent', max_length=10),
        ),
    ]
