# Generated by Django 4.2 on 2023-05-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='className',
            field=models.CharField(choices=[('fullcalendar-custom-event-hs-team', 'English'), ('fullcalendar-custom-event-tasks', 'Mathematics'), ('fullcalendar-custom-event-hs-team', 'Social Studies'), ('fullcalendar-custom-event-holidays', 'Science')], default='English', max_length=50, verbose_name='Class Theme'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='image',
            field=models.CharField(choices=[("{% static 'core/assets/svg/brands/mastercard.svg' %}", 'English'), ("{% static 'core/assets/svg/brands/excel-icon.svg' %}", 'Mathematics'), ("{% static 'core/assets/svg/brands/figma-icon.svg' %}", 'Social Studies'), ("{% static 'core/assets/svg/brands/pdf-icon.svg' %}", 'Science'), ("{% static 'core/assets/svg/brands/jira-icon.svg' %}", 'Religious Education'), ("{% static 'core/assets/svg/brands/slack-icon.svg' %}", 'Computer Studies')], default='English', max_length=60),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='repeatField',
            field=models.CharField(choices=[('weekdays', 'weekdays'), ('never', 'never'), ('everyday', 'everyday')], default='weekdays', max_length=10, verbose_name='Repeat Field'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='title',
            field=models.CharField(choices=[('English', 'English'), ('Mathematics', 'Mathematics'), ('Social Studies', 'Social Studies'), ('Science', 'Science'), ('Religious Education', 'Religious Education'), ('Computer Studies', 'Computer Studies')], default='English', max_length=50, verbose_name='Event Title'),
        ),
    ]
