# Generated by Django 4.0 on 2022-09-02 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_student_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='positions',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='school_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='user.png', upload_to='admin'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verified_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 2, 11, 4, 44, 554370)),
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(default='admin', max_length=20),
        ),
    ]
