# Generated by Django 4.0 on 2022-09-09 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_profile_positions_remove_profile_school_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='registration_number',
            field=models.CharField(default='2022/STD/1', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='user.png', upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_verified_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 9, 11, 55, 57, 352448)),
        ),
    ]
