# Generated by Django 4.0 on 2022-09-09 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_student_registration_number_alter_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='staff_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_verified_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 9, 17, 29, 17, 870890)),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(max_length=50),
        ),
    ]
