# Generated by Django 4.0 on 2023-01-04 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_teacher_email_teacher_staff_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='staff_number',
        ),
        migrations.AddField(
            model_name='student',
            name='unique_id',
            field=models.CharField(default='2022/STD/1', max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='unique_id',
            field=models.CharField(default='2022/TR/1', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_verified_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
