# Generated by Django 4.0 on 2023-01-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_student_registration_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='unique_id',
            field=models.CharField(default='2022/TR/10', max_length=50),
        ),
    ]
