# Generated by Django 4.0 on 2023-02-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_subject_teacher_subject3'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.CharField(default='Makerere Primary', max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.CharField(default='Makerere Primary', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject3',
            field=models.ManyToManyField(related_name='teachers', to='api.Subject', verbose_name='Subjects'),
        ),
    ]
