# Generated by Django 4.0 on 2023-02-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_student_school_teacher_school_alter_teacher_subject3'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.CharField(default='English', max_length=20),
        ),
    ]
