# Generated by Django 4.0 on 2023-02-26 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_attendance_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50, verbose_name='Event Title')),
                ('eventDescriptionLabel', models.CharField(max_length=50, verbose_name='Description')),
                ('eventLocationLabel', models.CharField(max_length=20, verbose_name='Venue')),
                ('repeatField', models.CharField(max_length=10, verbose_name='Repeat Field')),
                ('image', models.ImageField(default='figma-icon.svg', upload_to='timetable')),
                ('className', models.CharField(default='fullcalendar-custom-event-holidays', max_length=20, verbose_name='Color Theme')),
                ('start', models.DateTimeField(verbose_name='Start Time')),
                ('end', models.DateTimeField(verbose_name='End Time')),
                ('allDays', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guestsField', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='api.teacher', verbose_name='teacher')),
            ],
            options={
                'verbose_name': 'Timetable',
            },
        ),
    ]
